### ISSUE TITLE
"unknown compression method" during creating index

### ISSUE THREAD

**Issue by mmilosz** [ciscorn/ldoce5viewer#24]
Hi,

I've got following error when tried to create index on Ubuntu 14.04. I'm sure that ldoce data are correct, because I've successfully created index by using the same repository on Windows. Please let me know if any other information would be helpful.

BTW: Great application :)

Building the file-location lookup table...
Analyzing 'picture'...
Analyzing 'fs'...
Analyzing 'gb_hwd_pron'...
Analyzing 'sfx'...
Analyzing 'sound'...
Analyzing 'thesaurus'...
Analyzing 'etymologies'...
Analyzing 'examples'...
Analyzing 'activator_concept'...
Error occurred
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/indexer.py", line 437, in run
self._make_filemap()
File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/indexer.py", line 409, in _make_filemap
for (name, location) in file_iter:
File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/ldoce5/filemap.py", line 74, in list_files
root = et.fromstring(arch_reader.read(location))
File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/ldoce5/idmreader.py", line 229, in read
self._cache = decompress(f.read(cmpsize))
error: Error -3 while decompressing data: unknown compression method
Removing files...
Failed to create index

Best Regards,
Milosz

**Comment by mmilosz** [comment]
Sorry, this issue was connected with using dislocker. So I'm closing.
