### ISSUE TITLE
error message when I press the sound icon in Windows 10

### ISSUE THREAD

**Issue by diuwpor39io** [ciscorn/ldoce5viewer#25]
that is the message:

Traceback (most recent call last):
  File "ldoce5viewer\main.pyo", line 519, in finished
  File "ldoce5viewer\utils\soundplayer.pyo", line 124, in play
  File "ldoce5viewer\utils\mp3play\__init__.pyo", line 10, in load
  File "ldoce5viewer\utils\mp3play\__init__.pyo", line 17, in __init__
  File "ldoce5viewer\utils\mp3play\windows.pyo", line 44, in __init__
Exception: Ha ocurrido un problema al inicializar MCI.
this mean "Exception occurred while initializing MCI" what is?
I have VLC player for mp3, visual 2008 c++ 9.0.30729 (more vc really), win10. Help?

**Comment by mujeebhistorian** [comment]
![err](https://user-images.githubusercontent.com/37399769/37567347-f3992214-2a82-11e8-8d03-0f7ab72a07d2.PNG)

**Comment by mujeebhistorian** [comment]
Same error here. I am using Windows 10 (2017 october update). Please help. I am not a programmer. Any patch or update would be much appreciated. Thanks in advance.
