### ISSUE TITLE
Can't run on Archlinux after updating system

### ISSUE THREAD

**Issue by arashm** [ciscorn/ldoce5viewer#27]
I'm getting following error when trying to run ldoce5viewer on Archlinux:

```
Traceback (most recent call last):
  File "/usr/bin/ldoce5viewer", line 9, in <module>
    sys.exit(qtgui.run(sys.argv))
  File "/usr/lib/python3.4/site-packages/ldoce5viewer/qtgui/__init__.py", line 98, in run
    from .main import MainWindow
  File "/usr/lib/python3.4/site-packages/ldoce5viewer/qtgui/main.py", line 40, in <module>
    from .utils.soundplayer import create_soundplayer
  File "/usr/lib/python3.4/site-packages/ldoce5viewer/qtgui/utils/soundplayer.py", line 15, in <module>
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'
```

I have `gstreamer 1.6` and `phonon-qt4-gstreamer 4.8.2` installed on system.

**Comment by alm413** [comment]
Hi Arash

Follow the steps instructed in 

http://manjaro-tr.org/forum/index.php?topic=975.msg8772;topicseen#msg8772

That worked for me. Remember to mention python2.7 when you happen to execute a python script.
