### ISSUE TITLE
can not indexing succefully

### ISSUE THREAD

**Issue by crokobit** [ciscorn/ldoce5viewer#28]
```
209518 items were added.
Finalizing...
Done.
Building the full text search index for headwords and phrases...
Error occurred
Traceback (most recent call last):
File "ldoce5viewer/qtgui/indexer.pyc", line 438, in run
File "ldoce5viewer/qtgui/indexer.pyc", line 397, in _make_index
File "ldoce5viewer/qtgui/indexer.pyc", line 343, in make_full_hp
File "ldoce5viewer/fulltext.pyc", line 167, in __init__
File "whoosh/index.pyc", line 463, in writer
IOError: zipimport: can not open file /Users/haha/Downloads/LDOCE5 Viewer.app/Contents/Resources/lib/python2.7/site-packages.zip
Removing files...
Failed to create index
```

Thanks.

**Comment by crokobit** [comment]
indexing succefully after restarting my mac. :sob:
