### ISSUE TITLE
Error - Ubuntu MATE 16.04 LTS

### ISSUE THREAD

**Issue by minhja92** [ciscorn/ldoce5viewer#45]
When I opened ldoce5viewer in Terminal, the following appears:

$ ldoce5viewer
Traceback (most recent call last):
  File "/usr/local/bin/ldoce5viewer", line 9, in <module>
    sys.exit(qtgui.run(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/__init__.py", line 98, in run
    from .main import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/main.py", line 35, in <module>
    from . import indexer
  File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/indexer.py", line 29, in <module>
    from .ui.indexer import Ui_Dialog
ImportError: cannot import name Ui_Dialog

**Comment by linluc** [comment]
Seems like some Qt packages are missing. Running ldoce5viewer on Mint 18.1 (which is based on Ubuntu 16.04)  with python 2.7 and everything works, including the sound. Make sure all libs mentioned in README.md are installed.
