### ISSUE TITLE
ImportError: No module named collectors

### ISSUE THREAD

**Issue by blogkit** [ciscorn/ldoce5viewer#5]
ciscorn: Hi!
I run on Debian wheezy GNOME 64-bit.
I did all "Readme" said.
when I run ldoce5viewer in gnome-terminal, something wrong:
broterest@debian-dragon:~$ ldoce5viewer 
Traceback (most recent call last):
  File "/usr/local/bin/ldoce5viewer", line 9, in <module>
    sys.exit(qtgui.run(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/**init**.py", line 98, in run
    from .main import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/qtgui/main.py", line 28, in <module>
    from .. import fulltext
  File "/usr/local/lib/python2.7/dist-packages/ldoce5viewer/fulltext.py", line 17, in <module>
    from whoosh.collectors import WrappingCollector, \
ImportError: No module named collectors

How to fix it?
Thanks a lot.

**Comment by NhanNguyenMinh** [comment]
You have saved my time. Thank you ciscorn.
